import { Achievement } from '../types/game';

// 90+ Achievement system with tool mastery badges and rUv tributes
export const achievementsData: Achievement[] = [
  // Tutorial & Progression (10 achievements)
  {
    id: 'first-steps',
    name: 'First Steps',
    description: 'Complete your first tutorial step',
    icon: '👶',
    category: 'progression',
    rarity: 'common',
    xpReward: 10,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'tutorial-master',
    name: 'Tutorial Master',
    description: 'Complete the entire tutorial',
    icon: '🎓',
    category: 'progression',
    rarity: 'common',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'level-5',
    name: 'Rising Star',
    description: 'Reach level 5',
    icon: '⭐',
    category: 'progression',
    rarity: 'common',
    xpReward: 50,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'level-10',
    name: 'Expert Practitioner',
    description: 'Reach level 10',
    icon: '💫',
    category: 'progression',
    rarity: 'rare',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'level-25',
    name: 'Master of Flow',
    description: 'Reach level 25',
    icon: '🌟',
    category: 'progression',
    rarity: 'epic',
    xpReward: 250,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'level-50',
    name: 'Flow Grandmaster',
    description: 'Reach level 50',
    icon: '✨',
    category: 'progression',
    rarity: 'legendary',
    xpReward: 500,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'first-command',
    name: 'Command Initiate',
    description: 'Execute your first Claude Flow command',
    icon: '⚡',
    category: 'progression',
    rarity: 'common',
    xpReward: 25,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'command-veteran',
    name: 'Command Veteran',
    description: 'Execute 100 commands',
    icon: '🎖️',
    category: 'progression',
    rarity: 'rare',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 100,
  },
  {
    id: 'command-master',
    name: 'Command Master',
    description: 'Execute 500 commands',
    icon: '🏆',
    category: 'progression',
    rarity: 'epic',
    xpReward: 300,
    unlocked: false,
    progress: 0,
    maxProgress: 500,
  },
  {
    id: 'thousand-commands',
    name: 'Thousand Commands',
    description: 'Execute 1000 commands',
    icon: '💎',
    category: 'progression',
    rarity: 'legendary',
    xpReward: 500,
    unlocked: false,
    progress: 0,
    maxProgress: 1000,
  },

  // Swarm Mastery (15 achievements)
  {
    id: 'swarm-creator',
    name: 'Swarm Creator',
    description: 'Create your first swarm',
    icon: '🐝',
    category: 'swarm-mastery',
    rarity: 'common',
    xpReward: 50,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'mesh-master',
    name: 'Mesh Master',
    description: 'Master the mesh topology',
    icon: '🕸️',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'hierarchical-commander',
    name: 'Hierarchical Commander',
    description: 'Excel at hierarchical swarm management',
    icon: '⛰️',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ring-orchestrator',
    name: 'Ring Orchestrator',
    description: 'Perfect the ring topology coordination',
    icon: '💍',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'star-conductor',
    name: 'Star Conductor',
    description: 'Command star topology like a maestro',
    icon: '⭐',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'topology-sage',
    name: 'Topology Sage',
    description: 'Master all four topologies',
    icon: '🧙‍♂️',
    category: 'swarm-mastery',
    rarity: 'epic',
    xpReward: 200,
    unlocked: false,
    progress: 0,
    maxProgress: 4,
  },
  {
    id: 'agent-whisperer',
    name: 'Agent Whisperer',
    description: 'Spawn 50 different agents',
    icon: '🗣️',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 50,
  },
  {
    id: 'swarm-architect',
    name: 'Swarm Architect',
    description: 'Design the perfect swarm setup',
    icon: '🏗️',
    category: 'swarm-mastery',
    rarity: 'epic',
    xpReward: 250,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'multi-swarm-commander',
    name: 'Multi-Swarm Commander',
    description: 'Manage 5 swarms simultaneously',
    icon: '👑',
    category: 'swarm-mastery',
    rarity: 'legendary',
    xpReward: 400,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'efficiency-expert',
    name: 'Efficiency Expert',
    description: 'Achieve 95%+ swarm efficiency',
    icon: '📈',
    category: 'swarm-mastery',
    rarity: 'epic',
    xpReward: 200,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'task-juggler',
    name: 'Task Juggler',
    description: 'Orchestrate 20 tasks simultaneously',
    icon: '🤹',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 20,
  },
  {
    id: 'coordination-master',
    name: 'Coordination Master',
    description: 'Perfect swarm coordination patterns',
    icon: '🎭',
    category: 'swarm-mastery',
    rarity: 'epic',
    xpReward: 300,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'load-balancer',
    name: 'Load Balancer',
    description: 'Achieve perfect load distribution',
    icon: '⚖️',
    category: 'swarm-mastery',
    rarity: 'rare',
    xpReward: 125,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'swarm-healer',
    name: 'Swarm Healer',
    description: 'Master fault tolerance and recovery',
    icon: '🏥',
    category: 'swarm-mastery',
    rarity: 'epic',
    xpReward: 200,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'performance-tuner',
    name: 'Performance Tuner',
    description: 'Optimize swarm performance to perfection',
    icon: '🔧',
    category: 'swarm-mastery',
    rarity: 'epic',
    xpReward: 250,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },

  // Tool Proficiency (20 achievements)
  {
    id: 'swarm-init-master',
    name: 'Swarm Initiator',
    description: 'Master the swarm_init command',
    icon: '🚀',
    category: 'tool-proficiency',
    rarity: 'common',
    xpReward: 30,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'agent-spawn-expert',
    name: 'Agent Spawner',
    description: 'Become expert at spawning agents',
    icon: '👥',
    category: 'tool-proficiency',
    rarity: 'common',
    xpReward: 30,
    unlocked: false,
    progress: 0,
    maxProgress: 25,
  },
  {
    id: 'task-orchestration-pro',
    name: 'Task Orchestration Pro',
    description: 'Master task orchestration',
    icon: '🎼',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 50,
    unlocked: false,
    progress: 0,
    maxProgress: 15,
  },
  {
    id: 'memory-sage',
    name: 'Memory Sage',
    description: 'Master memory management commands',
    icon: '🧠',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 20,
  },
  {
    id: 'neural-trainer',
    name: 'Neural Trainer',
    description: 'Expert at neural network training',
    icon: '🧬',
    category: 'tool-proficiency',
    rarity: 'epic',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'performance-analyst',
    name: 'Performance Analyst',
    description: 'Master performance monitoring tools',
    icon: '📊',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 60,
    unlocked: false,
    progress: 0,
    maxProgress: 15,
  },
  {
    id: 'github-integrator',
    name: 'GitHub Integrator',
    description: 'Master GitHub integration commands',
    icon: '🐙',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 80,
    unlocked: false,
    progress: 0,
    maxProgress: 12,
  },
  {
    id: 'workflow-wizard',
    name: 'Workflow Wizard',
    description: 'Create magical automation workflows',
    icon: '🪄',
    category: 'tool-proficiency',
    rarity: 'epic',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 8,
  },
  {
    id: 'security-guardian',
    name: 'Security Guardian',
    description: 'Master security scanning tools',
    icon: '🛡️',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 90,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'backup-keeper',
    name: 'Backup Keeper',
    description: 'Master backup and restore systems',
    icon: '💾',
    category: 'tool-proficiency',
    rarity: 'common',
    xpReward: 40,
    unlocked: false,
    progress: 0,
    maxProgress: 8,
  },
  {
    id: 'terminal-ninja',
    name: 'Terminal Ninja',
    description: 'Master terminal command execution',
    icon: '🥷',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 70,
    unlocked: false,
    progress: 0,
    maxProgress: 20,
  },
  {
    id: 'config-master',
    name: 'Configuration Master',
    description: 'Excel at configuration management',
    icon: '⚙️',
    category: 'tool-proficiency',
    rarity: 'common',
    xpReward: 35,
    unlocked: false,
    progress: 0,
    maxProgress: 12,
  },
  {
    id: 'feature-detective',
    name: 'Feature Detective',
    description: 'Master feature detection systems',
    icon: '🕵️',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 55,
    unlocked: false,
    progress: 0,
    maxProgress: 8,
  },
  {
    id: 'log-whisperer',
    name: 'Log Whisperer',
    description: 'Master log analysis and insights',
    icon: '📝',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 65,
    unlocked: false,
    progress: 0,
    maxProgress: 15,
  },
  {
    id: 'diagnostic-doctor',
    name: 'Diagnostic Doctor',
    description: 'Expert at system diagnostics',
    icon: '🩺',
    category: 'tool-proficiency',
    rarity: 'epic',
    xpReward: 85,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'cache-commander',
    name: 'Cache Commander',
    description: 'Master coordination cache management',
    icon: '💨',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 50,
    unlocked: false,
    progress: 0,
    maxProgress: 12,
  },
  {
    id: 'state-keeper',
    name: 'State Keeper',
    description: 'Master state snapshots and restoration',
    icon: '📷',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 8,
  },
  {
    id: 'benchmark-champion',
    name: 'Benchmark Champion',
    description: 'Master performance benchmarking',
    icon: '🏁',
    category: 'tool-proficiency',
    rarity: 'epic',
    xpReward: 120,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'metrics-collector',
    name: 'Metrics Collector',
    description: 'Expert at system metrics collection',
    icon: '📈',
    category: 'tool-proficiency',
    rarity: 'rare',
    xpReward: 60,
    unlocked: false,
    progress: 0,
    maxProgress: 15,
  },
  {
    id: 'all-tools-master',
    name: 'Universal Tool Master',
    description: 'Master all 54+ Claude Flow tools',
    icon: '🔮',
    category: 'tool-proficiency',
    rarity: 'legendary',
    xpReward: 1000,
    unlocked: false,
    progress: 0,
    maxProgress: 54,
  },

  // Neural Networks (10 achievements)
  {
    id: 'neural-awakening',
    name: 'Neural Awakening',
    description: 'Train your first neural pattern',
    icon: '🧠',
    category: 'neural-networks',
    rarity: 'common',
    xpReward: 40,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'pattern-recognizer',
    name: 'Pattern Recognizer',
    description: 'Successfully recognize 100 patterns',
    icon: '👁️',
    category: 'neural-networks',
    rarity: 'rare',
    xpReward: 80,
    unlocked: false,
    progress: 0,
    maxProgress: 100,
  },
  {
    id: 'cognitive-enhancer',
    name: 'Cognitive Enhancer',
    description: 'Improve agent cognitive abilities',
    icon: '🚀',
    category: 'neural-networks',
    rarity: 'epic',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ensemble-creator',
    name: 'Ensemble Creator',
    description: 'Create powerful model ensembles',
    icon: '🎭',
    category: 'neural-networks',
    rarity: 'epic',
    xpReward: 200,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'transfer-master',
    name: 'Transfer Learning Master',
    description: 'Master transfer learning across domains',
    icon: '🔄',
    category: 'neural-networks',
    rarity: 'legendary',
    xpReward: 300,
    unlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'neural-compressor',
    name: 'Neural Compressor',
    description: 'Efficiently compress neural models',
    icon: '🗜️',
    category: 'neural-networks',
    rarity: 'rare',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'wasm-optimizer',
    name: 'WASM Optimizer',
    description: 'Master WASM SIMD acceleration',
    icon: '⚡',
    category: 'neural-networks',
    rarity: 'epic',
    xpReward: 180,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'inference-speedster',
    name: 'Inference Speedster',
    description: 'Achieve lightning-fast neural inference',
    icon: '💨',
    category: 'neural-networks',
    rarity: 'rare',
    xpReward: 120,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'neural-explainer',
    name: 'Neural Explainer',
    description: 'Master AI explainability techniques',
    icon: '🔍',
    category: 'neural-networks',
    rarity: 'epic',
    xpReward: 160,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'adaptive-learner',
    name: 'Adaptive Learner',
    description: 'Perfect adaptive learning systems',
    icon: '🧬',
    category: 'neural-networks',
    rarity: 'legendary',
    xpReward: 400,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },

  // Memory Management (8 achievements)
  {
    id: 'memory-keeper',
    name: 'Memory Keeper',
    description: 'Store your first memory',
    icon: '💾',
    category: 'memory-management',
    rarity: 'common',
    xpReward: 25,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'namespace-organizer',
    name: 'Namespace Organizer',
    description: 'Master memory namespace management',
    icon: '📁',
    category: 'memory-management',
    rarity: 'rare',
    xpReward: 60,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'persistence-master',
    name: 'Persistence Master',
    description: 'Achieve cross-session memory persistence',
    icon: '🔄',
    category: 'memory-management',
    rarity: 'epic',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'backup-guardian',
    name: 'Backup Guardian',
    description: 'Safely backup and restore memory',
    icon: '🛡️',
    category: 'memory-management',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'compression-expert',
    name: 'Compression Expert',
    description: 'Efficiently compress memory data',
    icon: '🗜️',
    category: 'memory-management',
    rarity: 'rare',
    xpReward: 80,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'sync-coordinator',
    name: 'Sync Coordinator',
    description: 'Synchronize memory across instances',
    icon: '🔄',
    category: 'memory-management',
    rarity: 'epic',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'memory-analyst',
    name: 'Memory Analyst',
    description: 'Analyze memory usage patterns',
    icon: '📊',
    category: 'memory-management',
    rarity: 'rare',
    xpReward: 70,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ttl-master',
    name: 'TTL Master',
    description: 'Master time-to-live memory management',
    icon: '⏰',
    category: 'memory-management',
    rarity: 'epic',
    xpReward: 120,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },

  // GitHub Integration (7 achievements)
  {
    id: 'repo-analyzer',
    name: 'Repository Analyzer',
    description: 'Analyze your first repository',
    icon: '🔍',
    category: 'github-integration',
    rarity: 'common',
    xpReward: 30,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'pr-master',
    name: 'Pull Request Master',
    description: 'Master pull request management',
    icon: '🔄',
    category: 'github-integration',
    rarity: 'rare',
    xpReward: 75,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'code-reviewer',
    name: 'Code Reviewer',
    description: 'Excel at automated code review',
    icon: '👀',
    category: 'github-integration',
    rarity: 'rare',
    xpReward: 80,
    unlocked: false,
    progress: 0,
    maxProgress: 15,
  },
  {
    id: 'issue-tracker',
    name: 'Issue Tracker',
    description: 'Master issue tracking and triage',
    icon: '🎯',
    category: 'github-integration',
    rarity: 'common',
    xpReward: 50,
    unlocked: false,
    progress: 0,
    maxProgress: 20,
  },
  {
    id: 'release-coordinator',
    name: 'Release Coordinator',
    description: 'Coordinate perfect releases',
    icon: '🚀',
    category: 'github-integration',
    rarity: 'epic',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'workflow-automator',
    name: 'Workflow Automator',
    description: 'Create seamless workflow automation',
    icon: '⚙️',
    category: 'github-integration',
    rarity: 'epic',
    xpReward: 200,
    unlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'multi-repo-conductor',
    name: 'Multi-Repo Conductor',
    description: 'Orchestrate multiple repositories',
    icon: '🎼',
    category: 'github-integration',
    rarity: 'legendary',
    xpReward: 300,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },

  // Performance (5 achievements)
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    description: 'Achieve lightning-fast execution',
    icon: '⚡',
    category: 'performance',
    rarity: 'rare',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'efficiency-guru',
    name: 'Efficiency Guru',
    description: 'Optimize for maximum efficiency',
    icon: '📈',
    category: 'performance',
    rarity: 'epic',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'bottleneck-hunter',
    name: 'Bottleneck Hunter',
    description: 'Identify and eliminate bottlenecks',
    icon: '🎯',
    category: 'performance',
    rarity: 'rare',
    xpReward: 120,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'resource-optimizer',
    name: 'Resource Optimizer',
    description: 'Perfect resource utilization',
    icon: '⚖️',
    category: 'performance',
    rarity: 'epic',
    xpReward: 180,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'performance-prophet',
    name: 'Performance Prophet',
    description: 'Predict and prevent performance issues',
    icon: '🔮',
    category: 'performance',
    rarity: 'legendary',
    xpReward: 400,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },

  // rUv Tribute Easter Eggs (10 achievements)
  {
    id: 'ruv-tribute-founder',
    name: 'rUv Tribute: The Founder',
    description: 'Discovered the creator of Claude Flow',
    icon: '👑',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 500,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'ruv-mode-activated',
    name: 'rUv Mode Activated',
    description: 'Unleashed maximum power mode',
    icon: '⚡',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 750,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'neural-architect-tribute',
    name: 'Neural Architect Tribute',
    description: 'Honor to the master of neural swarms',
    icon: '🧠',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 600,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'ascension-master',
    name: 'The Ascension Master',
    description: 'You understand the true meaning',
    icon: '🌟',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 1000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'ruv-legacy',
    name: 'rUv Legacy',
    description: 'Keeper of the Claude Flow legacy',
    icon: '🏛️',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 800,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'innovation-pioneer',
    name: 'Innovation Pioneer',
    description: 'Following in the footsteps of greatness',
    icon: '🚀',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 650,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'swarm-visionary',
    name: 'Swarm Visionary',
    description: 'Embracing the vision of collective intelligence',
    icon: '👁️‍🗨️',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 700,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'flow-philosopher',
    name: 'Flow Philosopher',
    description: 'Understanding the deeper meaning of Flow',
    icon: '🧙',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 550,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },
  {
    id: 'tribute-collector',
    name: 'Tribute Collector',
    description: 'Found all rUv tribute easter eggs',
    icon: '💎',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 2000,
    unlocked: false,
    progress: 0,
    maxProgress: 8,
    hidden: true,
  },
  {
    id: 'ultimate-tribute',
    name: 'Ultimate Tribute',
    description: 'The highest honor - rUv would be proud',
    icon: '👨‍💻',
    category: 'ruv-tribute',
    rarity: 'ruv-tribute',
    xpReward: 5000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    hidden: true,
  },

  // Social & Easter Eggs (5 achievements)
  {
    id: 'secret-seeker',
    name: 'Secret Seeker',
    description: 'Found your first easter egg',
    icon: '🥚',
    category: 'easter-eggs',
    rarity: 'common',
    xpReward: 50,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'easter-hunter',
    name: 'Easter Hunter',
    description: 'Found 5 easter eggs',
    icon: '🐰',
    category: 'easter-eggs',
    rarity: 'rare',
    xpReward: 150,
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'mystery-solver',
    name: 'Mystery Solver',
    description: 'Solved hidden puzzles and challenges',
    icon: '🔍',
    category: 'easter-eggs',
    rarity: 'epic',
    xpReward: 200,
    unlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'community-builder',
    name: 'Community Builder',
    description: 'Share knowledge with other players',
    icon: '🤝',
    category: 'social',
    rarity: 'rare',
    xpReward: 100,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'mentor',
    name: 'The Mentor',
    description: 'Help others master Claude Flow',
    icon: '👨‍🏫',
    category: 'social',
    rarity: 'legendary',
    xpReward: 300,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
];

// Achievement categories for UI organization
export const achievementCategories = {
  'progression': '🎯 Progression',
  'swarm-mastery': '🐝 Swarm Mastery', 
  'tool-proficiency': '🔧 Tool Proficiency',
  'neural-networks': '🧠 Neural Networks',
  'memory-management': '💾 Memory Management',
  'github-integration': '🐙 GitHub Integration',
  'performance': '⚡ Performance',
  'easter-eggs': '🥚 Easter Eggs',
  'social': '🤝 Social',
  'ruv-tribute': '👑 rUv Tributes',
};

// Helper functions
export const getAchievementsByCategory = (category: string) => {
  return achievementsData.filter(achievement => achievement.category === category);
};

export const getUnlockedAchievements = (achievements: Achievement[]) => {
  return achievements.filter(achievement => achievement.unlocked);
};

export const getAchievementProgress = (achievement: Achievement) => {
  return achievement.maxProgress > 0 ? (achievement.progress / achievement.maxProgress) * 100 : 0;
};

export const calculateTotalXpFromAchievements = (achievements: Achievement[]) => {
  return achievements.reduce((total, achievement) => {
    return total + (achievement.unlocked ? achievement.xpReward : 0);
  }, 0);
};